### ISSUE TITLE
Nouvelle catégorie : Backend

### ISSUE THREAD

**Issue by PierreRtec** [stanams/passeport.dev.ressources#1]
Je pose ça là, ça peut être intéressant de la rajoutée !

**Comment by stanams** [comment]
Merci @PierreRtec pour ton retour! Dans le découpage actuel il n'y pas effectivement de section "Backend" à proprement parler, mais il y a API design, software architecture, observabilité et cloud infrastructure qui alimentent et traitent de pas mal de compétences backend. D'après toi ça vaudrait le coup d'avoir une section spécifique backend vraiment à part ? Tu mettrais quoi dedans compte tenu des autres catégories mentionnées ?

**Comment by PierreRtec** [comment]
En fait, je suis d'accord avec le découpage actuel. C'est plutôt pour la vision qu'on a de ses compétences et leur champ d'action.

Pour moi, la création d'une catégorie spécifique "Backend" pourrait aider à identifier clairement ses compétences, donc oui ça en vaut la peine (à voter bien entendu ! ;))

Ca pourrait donner une vision plus nette de la répartition des tâches en termes de dév' Front / Back.

On pourrait y inclure les aspects liés à :
- l'optimisation du traitement des données,
- à la gestion de la sécurité, 
- à la mise en œuvre des bases de données, 
- performances, 
- stress tests,
- etc.

Comme j'ai d'abord appris le back, je trouve ça encore plus important. Et comme tu as spécifiquement indiquer une catégorie backend, ça me paraissait logique ! 

Pierre

**Comment by stanams** [comment]
C'est intéressant comme retour.
Sur tes différents points:
- l'optimisation du traitement des données => ça couvre pas mal d'aspects parfois bien distinct. Dans la partie data modeling il y a des éléments qui permettent l'otpimisation du traitement (partitionnement, indexation, stratégie de cache etc...)
- à la gestion de la sécurité => idem, la sécurité se retrouve sous des aspects variés et complémentaires (sécurisation des API, auth, protection XSS, layers anti bots côté infra, encryption des données etc...). Je n'ai d'ailleurs pas tout mis encore sur les aspects de sécurité, mais d'une façon générale ils se distribuent sur plusieurs domaines différents
- à la mise en œuvre des bases de données => dans la partie data modeling il y a pas mal de types de db différentes évoquées, tu avais autre chose en tête ?
- performances => un peu comme la sécurité, la perf se gère sur plusieurs niveaux. J'en ai mis côté frontend, côté data modeling (stratégie de cache par exemple)
- stress tests => c'est vrai que c'est absent du découpage, ça meriterait d'être rajouté côté tests

Du coup j'ai le sentiment que ce qui serait pas mal ce serait que pour un poste défini (backend par exemple), d'avoir la liste des différentes skills dans les différentes catégories qui sont bonnes à avoir qui se highlight par exemple ? Qu'est ce que t'en penses ?
